// <auto-generated />
namespace EBinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReferenceNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReferenceNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201506111517339_ReferenceNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
