// <auto-generated />
namespace EBinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class homepageicons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(homepageicons));
        
        string IMigrationMetadata.Id
        {
            get { return "201507201240157_home page icons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
