//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder_Operator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDContext : DbContext
    {
        public CDContext()
            : base("name=CDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADInfo> ADInfoes { get; set; }
        public DbSet<SAPCostCenter> SAPCostCenters { get; set; }
        public DbSet<SAPEmployee> SAPEmployees { get; set; }
        public DbSet<SAPPart> SAPParts { get; set; }
    }
}
