//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder_Operator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.Cells = new HashSet<Cell>();
            this.References = new HashSet<Reference>();
        }
    
        public int PartID { get; set; }
        public string PartDesc { get; set; }
    
        public virtual ICollection<Cell> Cells { get; set; }
        public virtual ICollection<Reference> References { get; set; }
    }
}
