//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder_Operator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceType
    {
        public ReferenceType()
        {
            this.References = new HashSet<Reference>();
            this.Plants = new HashSet<Plant>();
            this.HomePagePlants = new HashSet<Plant>();
        }
    
        public int ReferenceTypeID { get; set; }
        public string TypeName_en { get; set; }
        public string TypeName_es { get; set; }
        public int ReferenceCategoryID { get; set; }
    
        public virtual ICollection<Reference> References { get; set; }
        public virtual ReferenceCategory ReferenceCategory { get; set; }
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual ICollection<Plant> HomePagePlants { get; set; }
    }
}
