//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder_Operator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public Reference()
        {
            this.Cells = new HashSet<Cell>();
            this.Departments = new HashSet<Department>();
            this.Parts = new HashSet<Part>();
            this.Plants = new HashSet<Plant>();
            this.Regions = new HashSet<Region>();
        }
    
        public int ReferenceID { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public string URL { get; set; }
        public System.DateTime FlagDate { get; set; }
        public int ReferenceTypeID { get; set; }
        public Nullable<int> DefaultPlantID { get; set; }
    
        public virtual ReferenceType ReferenceType { get; set; }
        public virtual ICollection<Cell> Cells { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Part> Parts { get; set; }
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
    }
}
