//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder_Operator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Plants = new HashSet<Plant>();
            this.References = new HashSet<Reference>();
        }
    
        public int RegionID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual ICollection<Reference> References { get; set; }
    }
}
