//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder_Operator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPCostCenter
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Company { get; set; }
        public string Hierarchy { get; set; }
        public string Responsible { get; set; }
        public string ResponsibleAlt { get; set; }
        public string ValidOn { get; set; }
        public Nullable<System.DateTime> ExpireOn { get; set; }
        public string CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<System.DateTime> ExpireOnTest { get; set; }
        public Nullable<bool> Erase { get; set; }
    }
}
