//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EbinderContext : DbContext
    {
        public EbinderContext()
            : base("name=EbinderContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cell> Cells { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<ReferenceCategory> ReferenceCategories { get; set; }
        public virtual DbSet<ReferenceType> ReferenceTypes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
