//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBinder.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EBinder.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Icon.
        /// </summary>
        public static string AddIcon {
            get {
                return ResourceManager.GetString("AddIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplyFilter.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Categories.
        /// </summary>
        public static string BackToCategories {
            get {
                return ResourceManager.GetString("BackToCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Cells.
        /// </summary>
        public static string BackToCells {
            get {
                return ResourceManager.GetString("BackToCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Departments.
        /// </summary>
        public static string BackToDepartments {
            get {
                return ResourceManager.GetString("BackToDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Plants.
        /// </summary>
        public static string BackToPlants {
            get {
                return ResourceManager.GetString("BackToPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to References.
        /// </summary>
        public static string BackToReferences {
            get {
                return ResourceManager.GetString("BackToReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Regions.
        /// </summary>
        public static string BackToRegions {
            get {
                return ResourceManager.GetString("BackToRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Users.
        /// </summary>
        public static string BackToUsers {
            get {
                return ResourceManager.GetString("BackToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than 40 characters.
        /// </summary>
        public static string CategoryNameTooLong {
            get {
                return ResourceManager.GetString("CategoryNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be more than 5 characters.
        /// </summary>
        public static string CategoryNameTooShort {
            get {
                return ResourceManager.GetString("CategoryNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell is required.
        /// </summary>
        public static string CellRequired {
            get {
                return ResourceManager.GetString("CellRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string Cells {
            get {
                return ResourceManager.GetString("Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Filter.
        /// </summary>
        public static string ChangeFilter {
            get {
                return ResourceManager.GetString("ChangeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link.
        /// </summary>
        public static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete reference.
        /// </summary>
        public static string DeleteRefError {
            get {
                return ResourceManager.GetString("DeleteRefError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is required.
        /// </summary>
        public static string DepartmentRequired {
            get {
                return ResourceManager.GetString("DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept.
        /// </summary>
        public static string Dept {
            get {
                return ResourceManager.GetString("Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details and Links.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBinder+ Administration.
        /// </summary>
        public static string EBinderTitle {
            get {
                return ResourceManager.GetString("EBinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove link.
        /// </summary>
        public static string FailedToUnlinkError {
            get {
                return ResourceManager.GetString("FailedToUnlinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a location to filter documents for that area.
        /// </summary>
        public static string FilterDescription {
            get {
                return ResourceManager.GetString("FilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only New/Flagged References.
        /// </summary>
        public static string FilterFlag {
            get {
                return ResourceManager.GetString("FilterFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only References from my area.
        /// </summary>
        public static string FilterGlobal {
            get {
                return ResourceManager.GetString("FilterGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only References without links.
        /// </summary>
        public static string FilterNoLink {
            get {
                return ResourceManager.GetString("FilterNoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Options.
        /// </summary>
        public static string FilterOptions {
            get {
                return ResourceManager.GetString("FilterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to flag this reference?.
        /// </summary>
        public static string FlagConfirmation {
            get {
                return ResourceManager.GetString("FlagConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Date.
        /// </summary>
        public static string FlagDate {
            get {
                return ResourceManager.GetString("FlagDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Icons.
        /// </summary>
        public static string HomeIcons {
            get {
                return ResourceManager.GetString("HomeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can only be 8 home page icons. Consider deleting one before you add another.
        /// </summary>
        public static string HomePageMaxIconError {
            get {
                return ResourceManager.GetString("HomePageMaxIconError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete icon.
        /// </summary>
        public static string IconDeleteError {
            get {
                return ResourceManager.GetString("IconDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageRequired.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked to.
        /// </summary>
        public static string LinkedTo {
            get {
                return ResourceManager.GetString("LinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reference already belongs to this area.
        /// </summary>
        public static string LinkExistsError {
            get {
                return ResourceManager.GetString("LinkExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than 25 characters.
        /// </summary>
        public static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be more that 3 characters.
        /// </summary>
        public static string NameTooShort {
            get {
                return ResourceManager.GetString("NameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plant already uses this icon.
        /// </summary>
        public static string PlantIconError {
            get {
                return ResourceManager.GetString("PlantIconError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlantIcons.
        /// </summary>
        public static string PlantIcons {
            get {
                return ResourceManager.GetString("PlantIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant is required.
        /// </summary>
        public static string PlantRequired {
            get {
                return ResourceManager.GetString("PlantRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plants.
        /// </summary>
        public static string Plants {
            get {
                return ResourceManager.GetString("Plants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Categories.
        /// </summary>
        public static string ReferenceCategories {
            get {
                return ResourceManager.GetString("ReferenceCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Category.
        /// </summary>
        public static string ReferenceCategory {
            get {
                return ResourceManager.GetString("ReferenceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Title.
        /// </summary>
        public static string ReferenceTitle {
            get {
                return ResourceManager.GetString("ReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        public static string ReferenceType {
            get {
                return ResourceManager.GetString("ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Types.
        /// </summary>
        public static string ReferenceTypes {
            get {
                return ResourceManager.GetString("ReferenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number is required.
        /// </summary>
        public static string RefNumberRequired {
            get {
                return ResourceManager.GetString("RefNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number must be less than 25 characters.
        /// </summary>
        public static string RefNumberTooLong {
            get {
                return ResourceManager.GetString("RefNumberTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number must be more than 3 characters.
        /// </summary>
        public static string RefNumberTooShort {
            get {
                return ResourceManager.GetString("RefNumberTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be less than 150 characters.
        /// </summary>
        public static string RefTitleTooLong {
            get {
                return ResourceManager.GetString("RefTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must me more than 5 characters.
        /// </summary>
        public static string RefTitleTooShort {
            get {
                return ResourceManager.GetString("RefTitleTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type is required.
        /// </summary>
        public static string RefTypeRequired {
            get {
                return ResourceManager.GetString("RefTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region is required.
        /// </summary>
        public static string RegionRequired {
            get {
                return ResourceManager.GetString("RegionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        public static string RemoveLink {
            get {
                return ResourceManager.GetString("RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this link?.
        /// </summary>
        public static string RemoveLinkConfirmation {
            get {
                return ResourceManager.GetString("RemoveLinkConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Dashboard.
        /// </summary>
        public static string ReturnToDashboard {
            get {
                return ResourceManager.GetString("ReturnToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a plant from the filter menu.
        /// </summary>
        public static string SelectAPlantError {
            get {
                return ResourceManager.GetString("SelectAPlantError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type must be less than 25 characters.
        /// </summary>
        public static string TypeTooLong {
            get {
                return ResourceManager.GetString("TypeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type must be more than 3 characters.
        /// </summary>
        public static string TypeTooShort {
            get {
                return ResourceManager.GetString("TypeTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is required.
        /// </summary>
        public static string URLRequired {
            get {
                return ResourceManager.GetString("URLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must be less than 250 characters.
        /// </summary>
        public static string URLTooLong {
            get {
                return ResourceManager.GetString("URLTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL must be more than 5 characters.
        /// </summary>
        public static string URLTooShort {
            get {
                return ResourceManager.GetString("URLTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is not yet registered with the EBinder+. Please contact your local EBinder+ adminstrator.
        /// </summary>
        public static string UsernameNotRegistered {
            get {
                return ResourceManager.GetString("UsernameNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type is required.
        /// </summary>
        public static string UserTypeRequired {
            get {
                return ResourceManager.GetString("UserTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workcenter #.
        /// </summary>
        public static string Workcenter {
            get {
                return ResourceManager.GetString("Workcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workcenter # must be 9 characters.
        /// </summary>
        public static string WorkcenterLength {
            get {
                return ResourceManager.GetString("WorkcenterLength", resourceCulture);
            }
        }
    }
}
